apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sample-task
spec:
  steps:
    - name: echo
      image: alpine
      script: |
        #!/bin/sh
        echo "This is a placeholder task."
