name: CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my-devcontainer -f .devcontainer/Dockerfile .

      - name: Run tests
        run: docker run --rm my-devcontainer pytest tests
